{"name": "test_login[argvals1]", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'base' referenced before assignment", "trace": "self = <allure_commons._allure.fixture object at 0x000001DA94D3B808>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n..\\..\\..\\..\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\allure_commons\\_allure.py:200: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.yield_fixture(scope ='function', autouse=True)\n    def base_fixture():\n        try:\n            prodpath = open(constants.ENVIRONMENT_PROPERTIES)\n            prod.load(prodpath)\n            #prod.list()\n            base = BasePage()\n            objlist.append(base)\n        except Exception:\n            pass\n    \n        yield locals()\n>       base.quit()\nE       UnboundLocalError: local variable 'base' referenced before assignment\n\nconftest.py:26: UnboundLocalError"}, "parameters": [{"name": "argvals", "value": "{'RunMode': 'y', 'Browsername': 'Firefox', 'Username': 'u2', 'Password': 'p2'}"}], "start": 1630604805715, "stop": 1630604805720, "uuid": "471f4695-506f-4fa4-93c0-fd4138cc2751", "historyId": "cc5c29e5e275ae64e4f906c386a0ead0", "testCaseId": "93a39feb8eb701231e6c069b76eeac98", "fullName": "testcases.test_login.TestLogin#test_login", "labels": [{"name": "tag", "value": "usefixture('base_fixture')"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "WTIN05200385L"}, {"name": "thread", "value": "68792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}