{"uuid": "5284fead-70ba-475f-b3d8-33a35c073419", "children": ["9ba8a3ae-3c26-4e9d-84db-7eacd7b4bee2"], "befores": [{"name": "base_fixture", "status": "broken", "statusDetails": {"message": "NameError: name 'allure' is not defined\n", "trace": "  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\SESA243476\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\SESA243476\\Documents\\JavaStudyPlan\\EclipseProject\\POM\\conftest.py\", line 16, in base_fixture\n    with allure.step(\"Initializing block....\"):\n"}, "start": 1630831762916, "stop": 1630831762916}], "start": 1630831762916, "stop": 1630831762931}